Design u is
eukarya-inc/test-nour pull request #2
Opened 2022-02-15 13:24 UTC by nina992

2022-02-16 17:22 UTC, issmail-basel requested changes
Please check code comments.

2022-02-16 17:22 UTC, issmail-basel commented on public/index.html
> +<!DOCTYPE html>
From the `README file`:
- We want you to develop the frontend of an web application using React and Typescript.  

So It was preferred to use TypeScript template:
`https://create-react-app.dev/docs/getting-started#creating-a-typescript-app`

2022-02-16 17:22 UTC, issmail-basel commented on src/Components/Applications/NewApplicationForm.js
> +  const Applier = useRef();
Lowercase constant variable names is preferred.
`const applier = useRef();`

2022-02-16 17:22 UTC, issmail-basel commented on src/Components/Users/UserCreate.js
> +    return <div></div>
Is this not finished?
BTW if you want just to wrap a components you can use `<></>` instead of div element.

2022-02-16 17:22 UTC, issmail-basel commented on src/Components/Users/UserTable.js
> +  const columns = useMemo(
Same as lat `useMemo` usage.

2022-02-16 17:22 UTC, issmail-basel commented on src/Pages/CreateApplication.js
> +   console.log(ApplicationData);
Remove logs.

2022-02-16 17:22 UTC, issmail-basel commented on src/store/ApplicationContext.js
> +  //   removeFavorite: (meetupId) => {},
Remove necessary comments from the PR.

2022-02-17 06:39 UTC, nina992 commented on public/index.html
> +    <!--
Done

2022-02-17 06:39 UTC, nina992 commented on src/Components/Applications/NewApplicationForm.js
> +  const Applier = useRef();
Done

2022-02-17 06:40 UTC, nina992 commented on src/Components/Users/UserCreate.js
> +    return <div></div>
yes , it is not finished , Noted

2022-02-17 06:40 UTC, nina992 commented on src/Components/Users/UserTable.js
> +  const [ViewUserModal, SetViewUserModal] = useState(false);
done

2022-02-17 06:40 UTC, nina992 commented on src/Pages/CreateApplication.js
> +   console.log(ApplicationData);
done

2022-02-17 06:40 UTC, nina992 commented on src/store/ApplicationContext.js
> +  //   removeFavorite: (meetupId) => {},
done

2022-02-17 06:46 UTC, nina992 commented on src/Components/Applications/ApplicationsTable.js
> +  const columns = useMemo(
I use (useMemo) in create-table hook because if I don't a new column array will be created each time the components re-rendered for whatever reason. but I will remove it

2022-02-17 06:46 UTC, nina992 commented on README.MD
> -# Coding Test for Nour
done

2022-02-18 06:56 UTC, merged